#!/usr/bin/env python

from openid.test import *
from twisted.internet import protocol
from twisted.web import http

expect(1)

@sdfg
def _():

  @untwisted.call
  class factory(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        content = '&'.join(map(untwisted.compose('openid.'.__add__, '='.join), (
          ('mode', 'checkid_setup'),
          ('return_to', 'http://example.com/return'))))

        ctx.sendCommand('POST', '/')

        ctx.sendHeader('Content-Length', len(content))

        ctx.endHeaders()

        ctx.transport.write(content)

      handleResponse = staticmethod(untwisted.partial(equal, ''.join((
        '<html>',
          '<head>',
            '<title></title>',
          '</head><body onload="document.forms[0].submit()">',
            '<form action="http://example.com/return" method="post">',
              '<input type="hidden" name="openid.mode" value="cancel"/>',
              '<input type="hidden" name="openid.ns" value="http://specs.openid.net/auth/2.0"/>',
              '<input type="submit" value="Continue"/>',
            '</form>',
            '<script>document.forms[0].style.display = "none"</script>',
          '</body>',
        '</html>'))))

  reactor.connectTCP('localhost', 5629, factory)
