#!/usr/bin/env python

from openid.test import *
from twisted.internet import protocol
from twisted.web import http

expect(1)

@sdfg
def _():

  @untwisted.call
  class factory(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        content = 'password='

        ctx.sendCommand('POST', '/cookie')

        ctx.sendHeader('Content-Length', len(content))

        ctx.endHeaders()

        ctx.transport.write(content)

      handleResponse = staticmethod(untwisted.partial(equal, ''.join((
        '<html>',
          '<head>',
            '<title></title>',
          '</head><body>',
            '<form method="post">',
              '<input name="password" type="password"/>',
              '<input type="submit"/>',
            '</form>',
          '</body>',
        '</html>'))))

  reactor.connectTCP('localhost', 5629, factory)
