#!/usr/bin/env python

import rfc6265, sys, time, untwisted
from random import random
from twisted.internet import reactor
from twisted.python import log
from twisted.web import http
from untwisted import db

opEndpoint = 'http://mail.nottheoilrig.com/openid'

log.startLogging(sys.stdout)

asdf = db.connect(db='cookie', user='root')
dbmail = db.connect(db='dbmail', user='dbmail')

@untwisted.call
class factory(http.HTTPFactory):
  class protocol(http.HTTPChannel):
    class requestFactory(http.Request):
      cookie = set()

      def requestReceived(ctx, method, resource, version):
        ctx.client = ctx.channel.transport.getPeer()
        ctx.clientproto = version

        # For log
        ctx.method = method
        ctx.uri = resource

        if '/cookie' == resource:
          if 'POST' == method:
            for cookieString in ctx.requestHeaders.getRawHeaders('Cookie', ()):
              for cookiePair in rfc6265.cookieString.match(cookieString, 'cookiePair ( cookieName, cookieValue )'):
                if 'openid' == str(cookiePair.cookieName):
                  ctx.cookie.discard(str(cookiePair.cookieValue))

            ctx.content.seek(0)
            params = http.parse_qs(ctx.content.read())

            password, = params['password']

            for cursor in dbmail:
              count, = cursor.execute('SELECT COUNT(*) FROM dbmail_users WHERE passwd = %s', password).next()

            if count:

              # US-ASCII characters excluding CTLs, whitespace DQUOTE, comma,
              # semicolon, and backslash
              alphabet = chr(0x21) + ''.join(map(chr, range(0x23, 0x2b + 1))) + ''.join(map(chr, range(0x2d, 0x3a + 1))) + ''.join(map(chr, range(0x3c, 0x5b + 1))) + ''.join(map(chr, range(0x5d, 0x7e + 1)))

              # Choose six letters from alphabet, at random
              letter = random()
              cookie = ''
              for _ in range(6):
                letter *= len(alphabet)
                cookie += alphabet[int(letter)]
                letter -= int(letter)

              ctx.cookie.add(cookie)

              ctx.setHeader('Set-Cookie', 'openid=' + cookie)

              ctx.redirect('/cookie')

              return ctx.finish()

          ctx.setHeader('Content-Type', 'text/html')

          ctx.write(''.join(('<html>',
              '<head>',
                '<title></title>',
              '</head><body>',
                '<form method="post">',
                  '<input name="password" type="password"/>',
                  '<input type="submit"/>',
                '</form>',
              '</body>',
            '</html>')))

          return ctx.finish()

        if 'GET' == method:
          _, query = resource.split('?', 1)
          params = http.parse_qs(query)

        elif 'POST' == method:
          ctx.content.seek(0)
          params = http.parse_qs(ctx.content.read())

          mode, = params['openid.mode']

          # All direct requests are HTTP POST
          if 'check_authentication' == mode:
            ctx.write(''.join(('is_valid:true\n',
              'ns:http://specs.openid.net/auth/2.0\n')))

            return ctx.finish()

        mode, = params['openid.mode']
        if 'checkid_setup' == mode:
          returnTo, = params['openid.return_to']

          # Default: return_to URL
          try:
            realm, = params['openid.realm']

          except KeyError:
            realm = returnTo

          else:

            # When present, the "openid.return_to" URL MUST match the
            # "openid.realm", or the OP MUST return an indirect error response
            if not returnTo.startswith(realm):
              ctx.setHeader('Content-Type', 'text/html')

              ctx.write(''.join(('<html>',
                '<head>',
                  '<title></title>',
                '</head><body onload="document.forms[0].submit()">',
                  '<form action="{}" method="post">'.format(returnTo))))

              for key, value in (('mode', 'error'),
                  ('ns', 'http://specs.openid.net/auth/2.0')):
                ctx.write('<input name="openid.{}" type="hidden" value="{}"/>'.format(key, value))

              ctx.write(''.join(('<input type="submit" value="Continue"/>',
                    '</form>',
                    '<script>document.forms[0].style.display = "none"</script>',
                  '</body>',
                '</html>')))

              return ctx.finish()

          for cookieString in ctx.requestHeaders.getRawHeaders('Cookie', ()):
            for cookiePair in rfc6265.cookieString.match(cookieString, 'cookiePair ( cookieName, cookieValue )'):
              if 'openid' == str(cookiePair.cookieName) and str(cookiePair.cookieValue) in ctx.cookie:
                try:
                  for cursor in asdf:
                    sender, = cursor.execute('SELECT sender FROM address WHERE address = %s', realm).next()

                except StopIteration:
                  alphabet = '0123456789abcdefghijklmnopqrstuvwxyz'

                  # Choose six letters from alphabet, at random
                  letter = random()
                  sender = ''
                  for _ in range(6):
                    letter *= len(alphabet)
                    sender += alphabet[int(letter)]
                    letter -= int(letter)

                  for cursor in asdf:
                    cursor.execute('INSERT INTO address (address, sender) VALUES (%s, %s)', realm, sender)

                alias = {}
                for key, value in params.iteritems():
                  if key.startswith('openid.ns.'):
                    value, = value

                    alias[value] = key[len('openid.ns.'):]

                ctx.setHeader('Content-Type', 'text/html')

                ctx.write(''.join(('<html>',
                  '<head>',
                    '<title></title>',
                  '</head><body>',
                    realm,
                    '<form action="{}" method="post">'.format(returnTo))))

                for key, value in (('mode', 'cancel'),
                    ('ns', 'http://specs.openid.net/auth/2.0')):
                  ctx.write('<input name="openid.{}" type="hidden" value="{}"/>'.format(key, value))

                ctx.write(''.join(('<input type="submit" value="Reject"/>',
                  '</form><form action="{}" method="post">'.format(returnTo))))

                for key, value in (('assoc_handle', 'TODO'),
                    ('claimed_id', sender + '@nottheoilrig.com'),
                    ('identity', sender + '@nottheoilrig.com'),
                    ('mode', 'id_res'),
                    ('ns', 'http://specs.openid.net/auth/2.0'),
                    ('op_endpoint', opEndpoint),
                    ('response_nonce', time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())),
                    ('return_to', returnTo),
                    ('sig', 'TODO'),
                    ('signed', 'assoc_handle,claimed_id,identity,op_endpoint,response_nonce,return_to')):
                  ctx.write('<input name="openid.{}" type="hidden" value="{}"/>'.format(key, value))

                try:
                  axAlias = alias['http://openid.net/srv/ax/1.0']

                except KeyError:
                  pass

                else:
                  ctx.write(''.join(('<input name="openid.ns.{}" type="hidden" value="http://openid.net/srv/ax/1.0"/>'.format(axAlias),
                    '<input name="openid.{}.mode" type="hidden" value="fetch_response"/>'.format(axAlias))))

                  axType = {}
                  for key, value in params.iteritems():
                    if key.startswith('openid.{}.type.'.format(axAlias)):
                      value, = value

                      axType[key[len('openid.{}.type.'.format(axAlias)):]] = value

                for itm in 'openid.{}.if_available'.format(axAlias), 'openid.{}.required'.format(axAlias):
                  try:
                    attribute, = params[itm]

                  except (KeyError, UnboundLocalError):
                    pass

                  else:
                    ctx.write('<ul>')

                    for attribute in attribute.split(','):
                      ctx.write('<li>' + axType[attribute])

                      if axType[attribute] in ('http://schema.openid.net/namePerson', 'http://axschema.org/namePerson'):
                        ctx.write(''.join(('<input name="openid.{}.type.{}" type="hidden" value="{}"/>'.format(axAlias, attribute, axType[attribute]),
                          '<input name="openid.{}.value.{}" type="hidden" value="{}"/>'.format(axAlias, attribute, 'Jack Bates'))))

                      elif axType[attribute] in ('http://schema.openid.net/contact/email', 'http://axschema.org/contact/email'):
                        ctx.write(''.join(('<input name="openid.{}.type.{}" type="hidden" value="{}"/>'.format(axAlias, attribute, axType[attribute]),
                          '<input name="openid.{}.value.{}" type="hidden" value="{}@nottheoilrig.com"/>'.format(axAlias, attribute, sender))))

                      else:
                        raise Exception

                    ctx.write('</ul>')

                ctx.write(''.join(('<input type="submit" value="Approve"/>',
                      '</form>',
                    '</body>',
                  '</html>')))

                return ctx.finish()

          ctx.setHeader('Content-Type', 'text/html')

          ctx.write(''.join(('<html>',
            '<head>',
              '<title></title>',
            '</head><body onload="document.forms[0].submit()">',
              '<form action="{}" method="post">'.format(returnTo))))

          for key, value in (('mode', 'cancel'),
              ('ns', 'http://specs.openid.net/auth/2.0')):
            ctx.write('<input name="openid.{}" type="hidden" value="{}"/>'.format(key, value))

          ctx.write(''.join(('<input type="submit" value="Continue"/>',
                '</form>',
                '<script>document.forms[0].style.display = "none"</script>',
              '</body>',
            '</html>')))

        ctx.finish()

reactor.listenTCP(5629, factory, interface='localhost')

reactor.run()
